# file: nextcloud/roles/nginx/tasks/package.yml

- name: nginx | Add the nginx mainline package repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/debian/ {{ansible_distribution_release}} nginx'
    state: 'present'
  when: nginx_release_branch == 'mainline'

- name: nginx | Add the nginx stable package repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ {{ansible_distribution_release}} nginx'
    state: 'present'
  when: nginx_release_branch == 'stable'

- name: nginx | Make sure nginx is installed
  apt:
    pkg: '{{nginx}}'
    state: 'present'
    update_cache: yes
