- name: 'PHP | Ensure necessary dependencies are installed'
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - build-essential
    - libxml2-dev
