
- name: PHP | Download PHP source code
  get_url:
    url: '{{php_source_url}}'
    dest: '/tmp/{{php_version}}.tar.xz'
    checksum: 'sha256:{{php_sha256_checksum}}'

- name: PHP | Extract source code
  unarchive:
    src: '/tmp/{{php_version}}.tar.xz'
    dest: '/tmp'
    creates: '/tmp/{{php_version}}'
    copy: no
